apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: devhub-backendvva-pipeline-run-init
  namespace: devhub-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: devhub-backendvva-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https:////devhub-backendvva.git'
    - name: source-branch
      value: main
    - name: output-image
      value: //devhub-backendvva
  pipelineRef:
    name: devhub-backendvva-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
